base: config/graph_net/train_layout_graph.yaml
model:
  model_path:
  class_list: ['text', 'title', 'figure', 'table', 'list']
  class_map: {}
trainer:
  grad_clip: 5
  loss:
    class_weight_flag: true
    node_weight:
    edge_weight:
    loss_weight: -1
  save_epoch_freq: 1
  save_step_freq: 5000
  display_freq: 200
  epochs: 10
  eval_display_freq: 200
  eval_print_freq: 200
  print_freq: 200
  scheduler:
    scheduler_type: stairs
    warmup_epochs: 1
  save_dir: doclaynet/
  tensorboard_dir: doclaynet/tensorboard/
  resume_flag: true
  save_best: true
datasets:
  train:
    dataset:
      data_root:
        - dataset/publaynet
      label_root:
        - dataset/publaynet/preprocess/train
    num_workers: 6
    batch_size: 2
    collate_fn:
      aug_flag: false
  eval:
    dataset:
      data_root:
        - dataset/publaynet
      label_root:
        - dataset/publaynet/preprocess/val
